# Generated by Django 4.1.1 on 2022-10-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0027_alter_studies_options_alter_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="description",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="products",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
