# Generated by Django 4.1.1 on 2022-09-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_items_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
    ]
