# Generated by Django 4.1.1 on 2022-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_activity_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='activites',
            field=models.ManyToManyField(blank=True, null=True, to='base.activity'),
        ),
    ]
