# Generated by Django 4.1.1 on 2022-09-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_lectures_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='activites',
        ),
        migrations.AddField(
            model_name='lectures',
            name='activites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.activity'),
        ),
    ]
