# Generated by Django 4.1.1 on 2022-09-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_lectures_activites_lectures_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='activites',
        ),
    ]
