# Generated by Django 4.1.1 on 2022-09-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_lectures_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lecture',
        ),
        migrations.AddField(
            model_name='activity',
            name='lecture',
            field=models.ManyToManyField(to='base.lectures'),
        ),
    ]
