# Generated by Django 4.1.1 on 2022-09-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_activity_lecture_activity_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.activity'),
        ),
    ]
