# Generated by Django 4.1.1 on 2022-09-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_lectures_activities_remove_activity_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='activities', to='base.activity'),
        ),
    ]
