# Generated by Django 4.1.1 on 2022-09-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_lectures_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='activities',
            field=models.ManyToManyField(related_name='activities', to='base.activity'),
        ),
    ]
