# Generated by Django 4.1.1 on 2022-09-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_lectures_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='activities',
        ),
        migrations.AlterField(
            model_name='activity',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='base.lectures'),
        ),
    ]
