# Generated by Django 4.1.1 on 2022-09-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_activity_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['is_done']},
        ),
    ]
