# Generated by Django 4.1.1 on 2022-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='is_grade',
            field=models.BooleanField(default=False),
        ),
    ]
