# Generated by Django 4.1.1 on 2022-09-20 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_activity_weight_alter_grades_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='earned_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
