# Generated by Django 4.1.1 on 2022-09-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_lectures_earned_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='base.activity'),
        ),
    ]
