# Generated by Django 4.1.1 on 2022-09-22 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_activity_weight_studies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='how_many_minutes',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(6000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
