# Generated by Django 4.2.5 on 2023-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_transfercodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercodes',
            name='hall',
            field=models.CharField(default='A', max_length=200),
        ),
        migrations.AddField(
            model_name='transfercodes',
            name='meal',
            field=models.CharField(default='aksam', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfercodes',
            name='code',
            field=models.CharField(default='000000', max_length=200),
        ),
    ]
